# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sampleblog', '0003_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved_comment',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='hello'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('Tech', 'Tech'), ('Food', 'Food'), ('Travel', 'Travel'), ('Fashion', 'Fashion'), ('Fashion and trend', 'Fashion and trend')], max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
