# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sampleblog', '0004_auto_20170122_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
