# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleblog', '0005_comment_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('Economics', 'Economics'), ('Finance', 'Finance'), ('Pet', 'Pet'), ('Gaming', 'Gaming'), ('Nature', 'Nature'), ('Medical', 'Medical'), ('Social Media', 'Social Media'), ('Sports', 'Sports'), ('Science', 'Science'), ('Technology', 'Technology'), ('History', 'History'), ('Travel', 'Travel'), ('Fashion', 'Fashion'), ('Music', 'Music'), ('Movie', 'Movie'), ('Education', 'Education'), ('Health', 'Health')], max_length=50),
        ),
    ]
